name: Test Jupyter Notebook

# This workflow will run on any push to the master branch
on:
  push:
    branches:
      - master

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allow writing to repository contents (including creating releases)
      id-token: write  # Allow issuing id-token if needed by the `gh` command

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install jupyter

      # Step 4: Run the Jupyter notebook and convert it to HTML
      - name: Execute Jupyter Notebook and Convert to HTML
        run: |
          jupyter nbconvert --to html --execute MNIST-classification.ipynb

      # Step 5: Upload the generated HTML as an artifact
      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: notebook-report
          path: MNIST-classification.html
          
      # Step 6: Fail the action if the notebook run fails
      - name: Check for notebook errors
        run: |
          if grep -q 'Traceback' your_notebook.ipynb; then
            echo "Notebook execution failed. Cannot push to master."
            exit 1
          fi

      - name: Create a GitHub Release and Attach HTML File
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub automatically provides this token
        run: |
          # Use the current date as the release tag (e.g., "2025-03-24")
          RELEASE_TAG=$(date +'%Y-%m-%d')  # Get the current date as a tag
          gh release create $RELEASE_TAG MNIST-classification.html --title "MNIST Classification Report" --notes "This is the HTML report generated from running the MNIST classification notebook."
